version: '2'
services:
  db:
    image: postgres:10.11
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5772:5432"
  web:
    build: ./web
    container_name: web
    volumes:
      - .:/var/www/html/
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./web/config:/etc/apache2/sites-available
    depends_on:
      - db
    ports:
      - 8772:80